# Development Docker Compose - includes volume mounts for live development
version: '3.8'

services:
  irmin-server:
    build:
      context: .
      dockerfile: docker/irmin-server/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - IRMIN_PORT=8080
      - IRMIN_STORE_PATH=/data/irmin_store
    volumes:
      # Mount source code for development
      - ./ocaml-bridge:/home/opam/irmin-bridge/ocaml-bridge
      - ./dune-project:/home/opam/irmin-bridge/dune-project
      - ./irmin-bridge.opam:/home/opam/irmin-bridge/irmin-bridge.opam
      # Mount demo data
      - ./demo-data:/home/opam/data/irmin_store
    networks:
      - irmin-network
    command: >
      sh -c "
        eval $$(opam env) &&
        echo 'Development mode: rebuilding project...' &&
        cd /home/opam/irmin-bridge &&
        dune build &&
        dune install --prefix=/home/opam/.local &&
        echo 'Starting development server...' &&
        exec irmin-bridge-server --port 8080 --store /home/opam/data/irmin_store
      "

  # Development proxy for CORS during frontend development
  irmin-proxy:
    image: nginx:alpine
    ports:
      - "3001:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - irmin-server
    networks:
      - irmin-network

volumes:
  demo-data:
    driver: local

networks:
  irmin-network:
    driver: bridge